name: Deployment
on:
  push:
    branches:
      - main
      - dev
env: 
  PORT: 8080
  MONGODB_DB_NAME: ${{ vars.MONGODB_DB_NAME }}
  MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
jobs:
  test:
    environment: testing
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run server
        run: |
          echo "start & npx wait-on http://127.0.0.1:${{env.PORT}}"
      - name: Run tests
        run: npm test
        continue-on-error: true
      - name: Output information
        run: |        
          echo "db-name: $MONGODB_DB_NAME"
          echo "secret: $MONGODB_PASSWORD"
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |        
          echo "db-name: $MONGODB_DB_NAME"
          echo "secret: $MONGODB_PASSWORD"
